# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- cypressmain

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
   
- script: |
    npm install   
    npm install -g allure-commandline --save-dev  
    npm run smoketest:allure
    npm run report:allure    
  displayName: 'Run a multi-line script'
  
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'allure-report'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/allure-report' 
    publishLocation: 'Container'    
