# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- cypressmain

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
   
- script: |
    npm install   
    npm install -g allure-commandline --save-dev  
    npm run smoketest:allure
    npm run report:allure    
  displayName: 'Run a multi-line script'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/allure-report' 
    Contents: '**' # string. Required. Contents. Default: **.    
    TargetFolder: '$(Build.ArtifactStagingDirectory)' 
    
- task: PublishBuildArtifacts@1
  inputs:   
    PathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'allure-report'
    publishLocation: 'Container'    
- task: PublishTestResults@2
  displayName: publish allure test results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.html'
    searchFolder: 'allure-report'
    testRunTitle: ublish allure test results
    buildConfiguration: debug
    mergeTestResults: true